apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  namespace: tylerhine
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: ighost007/python-mysql:latest 
        ports:
        - containerPort: 3306
        resources:
          requests:
            cpu: 10m
