apiVersion: v1
kind: Service
metadata:
  name: sql-svc
  namespace: tylerhine
spec:
  selector:
    app: sql
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307
      nodePort: 32000
  type: NodePort
